### ISSUE TITLE
Error when playing a sample

### ISSUE THREAD

**Issue by fweidner** [JoReIMT/Dialogue-Sample-Player#3]
I'm trying to use the player on a surface tablet.

After checking out the develop branch, installing all prerequisites, I start the player via DialogueRun.bat.

Following error appears: 
<img width="427" alt="capture" src="https://user-images.githubusercontent.com/16336130/49088113-de92b300-f258-11e8-833b-eaf7a37f7f41.PNG">

**Comment by JoReIMT** [comment]
The develop branch is now up to date, it should be working now.
